### PR TITLE
Updating platform detection

### PR DESCRIPTION
**Pull request by cpb**

### CODE REVIEW

**Comment by larskanis** [comment]
What is the advantage of this change?

**Comment by cpb** [comment]
Supports jruby.

**Comment by cpb** [comment]
oops missed a commit

**Comment by larskanis** [comment]
Makes sense.

I still didn't release this gem, but it is on my agenda.

**Comment by larskanis** [comment]
Thank you!

**Comment by cpb** [comment]
Hey no problemo. It would be a good idea to release so that I can switch out the `git:` option in my Gemfile...

**Pull request merged**
